version: '3.8'
services:
  translation_server:
    container_name: translation_server
    image: lengoo/translation/server:2.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
networks:
  default:
    external:
      name: lengoo_mtx